# Generated by Django 5.2 on 2025-04-21 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_fees_date",
                    models.DateTimeField(verbose_name="Дата и время перевода"),
                ),
                (
                    "sum_invest",
                    models.IntegerField(
                        default=0, verbose_name="Сумма перевода"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_fees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Инвестор",
                    ),
                ),
            ],
        ),
    ]
