# Generated by Django 5.2 on 2025-04-22 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("money_fees", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={
                "verbose_name": "Инвестиция",
                "verbose_name_plural": "Инвестиции",
            },
        ),
        migrations.CreateModel(
            name="Collect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_fees",
                    models.CharField(
                        max_length=16, verbose_name="Название сбора"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Идентификатор страницы для URL; разрешены символы латиницы, цифры, дефис и подчёркивание.",
                        max_length=64,
                        unique=True,
                        verbose_name="Повод сбора",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "sum_fees",
                    models.IntegerField(
                        default=0, verbose_name="Запланированная сумма сбора"
                    ),
                ),
                (
                    "curr_sum_fees",
                    models.IntegerField(
                        default=0, verbose_name="Текущая сумма сбора"
                    ),
                ),
                (
                    "num_people",
                    models.IntegerField(
                        verbose_name="Количество инвестировавших"
                    ),
                ),
                (
                    "fees_date",
                    models.DateTimeField(
                        verbose_name="Дата и время завершения сбора"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_fees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор сбора",
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа сбора",
                "verbose_name_plural": "Группы сбора",
            },
        ),
        migrations.CreateModel(
            name="CollectUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "collect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="money_fees.collect",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="money_fees.payment",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="collect",
            name="collec_fees",
            field=models.ManyToManyField(
                through="money_fees.CollectUser", to="money_fees.payment"
            ),
        ),
    ]
