# Generated by Django 5.2 on 2025-04-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("money_fees", "0002_alter_payment_options_collect_collectuser_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collect",
            name="fees_date",
        ),
        migrations.AlterField(
            model_name="collect",
            name="num_people",
            field=models.IntegerField(
                default=0, verbose_name="Количество инвестировавших"
            ),
        ),
    ]
