# Generated by Django 5.2 on 2025-04-22 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "money_fees",
            "0003_remove_collect_fees_date_alter_collect_num_people",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collect",
            name="author",
        ),
    ]
