# Generated by Django 5.2 on 2025-04-22 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("money_fees", "0004_remove_collect_author"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collect",
            name="collec_fees",
        ),
        migrations.AlterModelOptions(
            name="collect",
            options={},
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={},
        ),
        migrations.RemoveField(
            model_name="collect",
            name="curr_sum_fees",
        ),
        migrations.RemoveField(
            model_name="collect",
            name="num_people",
        ),
        migrations.RemoveField(
            model_name="collect",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="collect",
            name="sum_fees",
        ),
        migrations.RemoveField(
            model_name="collect",
            name="title_fees",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="sum_invest",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="user_fees_date",
        ),
        migrations.AddField(
            model_name="collect",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="collect",
            name="collected_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="collect",
            name="cover_image",
            field=models.ImageField(null=True, upload_to="covers/"),
        ),
        migrations.AddField(
            model_name="collect",
            name="donors_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="collect",
            name="end_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="collect",
            name="reason",
            field=models.CharField(
                choices=[("birthday", "День рождения"), ("wedding", "Свадьба")],
                default="birthday",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="collect",
            name="target_amount",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name="collect",
            name="title",
            field=models.CharField(default="попытка", max_length=255),
        ),
        migrations.AddField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payment",
            name="collect",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="money_fees.collect",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="collect",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="CollectUser",
        ),
    ]
