# Generated by Django 5.2 on 2025-04-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "money_fees",
            "0005_remove_collect_collec_fees_alter_collect_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collect",
            name="cover_image",
        ),
        migrations.AddField(
            model_name="collect",
            name="image",
            field=models.ImageField(
                default=None, null=True, upload_to="images/"
            ),
        ),
    ]
