# Generated by Django 5.2 on 2025-04-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("money_fees", "0006_remove_collect_cover_image_collect_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collect",
            name="collected_amount",
        ),
        migrations.RemoveField(
            model_name="collect",
            name="reason",
        ),
        migrations.RemoveField(
            model_name="collect",
            name="target_amount",
        ),
        migrations.AddField(
            model_name="collect",
            name="curr_sum_fees",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Текущая сумма сбора",
            ),
        ),
        migrations.AddField(
            model_name="collect",
            name="slug",
            field=models.CharField(
                choices=[("birthday", "День рождения"), ("wedding", "Свадьба")],
                default="birthday",
                max_length=255,
                verbose_name="Повод сбора",
            ),
        ),
        migrations.AddField(
            model_name="collect",
            name="sum_fees",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Запланированная сумма сбора",
            ),
        ),
        migrations.AlterField(
            model_name="collect",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
    ]
