# Generated by Django 5.2 on 2025-04-22 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("money_fees", "0007_remove_collect_collected_amount_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collect",
            options={
                "verbose_name": "Группа сбора",
                "verbose_name_plural": "Группы сбора",
            },
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "Инвестиция", "verbose_name_plural": "Инвестиции"},
        ),
        migrations.RemoveField(
            model_name="payment",
            name="collect",
        ),
        migrations.CreateModel(
            name="CollectUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "collect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="money_fees.collect",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="money_fees.payment",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="collect",
            name="collec_fees",
            field=models.ManyToManyField(
                through="money_fees.CollectUser", to="money_fees.payment"
            ),
        ),
    ]
