# Generated by Django 5.2 on 2025-04-23 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "money_fees",
            "0009_remove_collect_collec_fees_payment_collec_fees_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="collec_fees",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fees",
                to="money_fees.collect",
            ),
        ),
    ]
