# Generated by Django 5.2 on 2025-05-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("money_fees", "0011_alter_collect_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collect",
            name="curr_sum_fees",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Текущая сумма сбора",
            ),
        ),
        migrations.AlterField(
            model_name="collect",
            name="donors_count",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="collect",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="collect",
            name="slug",
            field=models.CharField(
                blank=True,
                choices=[
                    ("birthday", "День рождения"),
                    ("wedding", "Свадьба"),
                ],
                default="birthday",
                max_length=255,
                verbose_name="Повод сбора",
            ),
        ),
    ]
